#!/usr/bin/env python
import rospy
from define_msg.msg import Int32

def callback(msg):
    print "subscribe: %d" % msg.data

rospy.init_node('accept_node')
sub = rospy.Subscriber('define_msg', Int32, callback)
rospy.spin()
